version: '2'
services:
    complainportal-app:
        image: complainportal
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://complainportal-postgresql:5432/complainportal
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    complainportal-postgresql:
        extends:
            file: postgresql.yml
            service: complainportal-postgresql
